<a href="https://colab.research.google.com/github/samitha278/CoreLlama/blob/main/positional_encoding_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

### Binary value function

In [55]:
def _get_binary(value):

    if value == 1 or value == 0 :
        return f"{value}"

    binary = f"{_get_binary(value//2)}{value%2}"

    return binary

bin = _get_binary(16)
print(bin)
bin_list = list(map(int,bin))
tensor = torch.tensor(bin_list)
print(tensor)

10000
tensor([1, 0, 0, 0, 0])


In [62]:
zeros = torch.zeros((4,6))
zeros[2,6-3:] = torch.tensor([1,2,3])
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 2., 3.],
        [0., 0., 0., 0., 0., 0.]])

## Binary Positional Encoding

In [61]:
class BinaryPE():

    def __init__(self,max_len,d_model):

        self.encoding = self._precompute_binary(max_len,d_model)


    def _get_binary(self,value):

        if value == 1 or value == 0 :
            return f"{value}"

        binary = f"{self._get_binary(value//2)}{value%2}"

        return binary


    def _precompute_binary(self,max_len,d_model):

        binary_table = torch.zeros((max_len,d_model))

        for pos in range(max_len):
            binary = list(map(int,self._get_binary(pos)))
            print(binary)

            binary_table[pos,d_model-len(binary):] = torch.tensor(binary)

        return binary_table



    def forward(self,ids):
        return self.encoding(ids)


In [59]:
binary_pe = BinaryPE(4,6)
binary_pe.encoding

[0]
[1]
[1, 0]
[1, 1]


tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 1.]])

## Sinusoidal Positional Encoding

## Rotary Positional Encoding - RoPE